/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class phylonet_coalescent_Polytree_PTNative */

#ifndef _Included_phylonet_coalescent_Polytree_PTNative
#define _Included_phylonet_coalescent_Polytree_PTNative
#ifdef __cplusplus
extern "C" {
#endif
#undef phylonet_coalescent_Polytree_PTNative_batchSize
#define phylonet_coalescent_Polytree_PTNative_batchSize 32L
/*
 * Class:     phylonet_coalescent_Polytree_PTNative
 * Method:    cppParse
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_phylonet_coalescent_Polytree_00024PTNative_cppParse
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     phylonet_coalescent_Polytree_PTNative
 * Method:    cppInit
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_phylonet_coalescent_Polytree_00024PTNative_cppInit
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     phylonet_coalescent_Polytree_PTNative
 * Method:    cppBatchCompute
 * Signature: ([J[[J[[J[[J)V
 */
JNIEXPORT void JNICALL Java_phylonet_coalescent_Polytree_00024PTNative_cppBatchCompute
  (JNIEnv *, jclass, jlongArray, jobjectArray, jobjectArray, jobjectArray);

/*
 * Class:     phylonet_coalescent_Polytree_PTNative
 * Method:    cppCountEqClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_phylonet_coalescent_Polytree_00024PTNative_cppCountEqClass
  (JNIEnv *, jclass);

/*
 * Class:     phylonet_coalescent_Polytree_PTNative
 * Method:    cppSupport
 * Signature: ([J[J[J[J)J
 */
JNIEXPORT jlong JNICALL Java_phylonet_coalescent_Polytree_00024PTNative_cppSupport
  (JNIEnv *, jclass, jlongArray, jlongArray, jlongArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
